name: Python FastAPI Deploy to EB

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: os-actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*" "*venv*" "__pycache__*"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ai-a
          environment_name: Ai-a-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2  # 서울 리전
          deployment_package: deploy.zip
          environment_vars: "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          use_existing_version_if_available: true 

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ai-a
          environment_name: Ai-b-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2  # 서울 리전
          deployment_package: deploy.zip
          environment_vars: "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          use_existing_version_if_available: true 